<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDown_Staff Management</name>
   <tag></tag>
   <elementGuidId>69c36361-f829-444c-a3ed-8be27612de7c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'q-item__section q-item__label' and (text() = 'Staff Management' or . = 'Staff Management')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(5) > div.q-expansion-item.q-item-type.q-expansion-item--collapsed.q-expansion-item--standard.text-blue-14 > div.q-expansion-item__container.relative-position > div.q-item.q-item-type.row.no-wrap.q-item--clickable.q-link.cursor-pointer.q-focusable.q-hoverable.no-padding > div.q-item__section.column.q-item__section--main.justify-center > div.q-item__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'q-expansion-item__content')]//div[contains(@class, 'q-item__label') and text()='Staff Management']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08ce3c0a-ea55-4ec3-8a6a-510410840e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-item__section q-item__label</value>
      <webElementGuid>36915b30-dfa4-4ac7-8f3b-5f17130804c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Management</value>
      <webElementGuid>9b9fadd9-91aa-4dcf-a63b-b95b178d0af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop no-touch body--light&quot;]/div[@id=&quot;q-app&quot;]/div[@id=&quot;q-app&quot;]/div[1]/div[@class=&quot;q-layout q-layout--standard&quot;]/div[@class=&quot;q-drawer-container&quot;]/aside[@class=&quot;q-drawer q-drawer--left q-drawer--bordered q-drawer--standard fixed&quot;]/div[@class=&quot;q-drawer__content fit scroll&quot;]/div[@class=&quot;q-list q-pl-xs text-blue-14 q-pb-xl q-mb-xl&quot;]/div[5]/div[@class=&quot;q-expansion-item q-item-type q-expansion-item--collapsed q-expansion-item--standard text-blue-14&quot;]/div[@class=&quot;q-expansion-item__container relative-position&quot;]/div[@class=&quot;q-item q-item-type row no-wrap q-item--clickable q-link cursor-pointer q-focusable q-hoverable no-padding&quot;]/div[@class=&quot;q-item__section column q-item__section--main justify-center&quot;]/div[@class=&quot;q-item__label&quot;]</value>
      <webElementGuid>a0cb98d9-4abb-4d98-b378-8d4c7f15d694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7b5e5fac-3919-4f84-ae96-ba53bdbbcb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e8eb8273-3385-4e56-a7fb-13f51e115542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e4ce995e-3e50-4f96-8f90-7dadc03476fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d89591e9-523a-49b2-abe2-264896473499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Card'])[1]/preceding::div[16]</value>
      <webElementGuid>b4bf972c-4f45-41b8-81d2-ffd58973fe73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Staff Management']/parent::*</value>
      <webElementGuid>7c975d68-6471-4b0f-bbb0-314e4003a3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/div</value>
      <webElementGuid>486a393a-e910-4180-be46-17861689acf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Staff Management' or . = 'Staff Management')]</value>
      <webElementGuid>7ead303a-58f2-4463-a450-63ed09f48e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[contains(@class, 'q-expansion-item__content') and contains(@class, 'relative-position')]//div[contains(@class, 'q-item__label')]</value>
      <webElementGuid>59ebb90b-50a3-42b0-8f5c-e86a6fb3b2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
