<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NameStaff</name>
   <tag></tag>
   <elementGuidId>559768ca-7448-4c28-8d1d-df6825bc7f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c915460e-20e3-4e95-afc0-4be96bcc6d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>b9aa3ebc-b319-412f-9986-00fe804b82d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56fc3335-56cb-49c3-92ae-50a7d7213996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      <webElementGuid>62e18dde-1b5c-42d5-9f5d-ed81a6b8f3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2f4c301f-2501-4383-b3d9-db342019c181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_757dd486-5af3-4359-85f5-6618c21ed046&quot;)</value>
      <webElementGuid>b611b110-0bac-443a-bd0f-06dc1a2623ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>90b49cfb-ee8b-4e39-8894-f200b99b5d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      <webElementGuid>17e0f455-b02c-4dda-84ea-eb7ef7504611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/label[2]/div/div/div/input</value>
      <webElementGuid>d929e81c-65e8-4627-b890-125fcf242744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div/div/input</value>
      <webElementGuid>b994f61d-ca9b-42d3-98b5-3011bea52e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_757dd486-5af3-4359-85f5-6618c21ed046' and @type = 'password']</value>
      <webElementGuid>63df0f26-a2cf-4671-828f-ff2fb8c0d454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
