<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>53b748e4-2162-4b95-8d57-ab8206a5604f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Password' and @type = 'password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b61e844-ebea-4c68-858c-cf547e42a749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>36142e4f-7a2a-46e6-bd7e-2903ae9abf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0304d446-4cd1-4b0b-af35-b411d3204e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>9d74a56e-5d0f-4478-bf11-d5549401283a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      <webElementGuid>ec01246b-6b4c-4d95-8a5f-291a8274a62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>caea5ec6-307d-48c8-a2f8-257574224e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_757dd486-5af3-4359-85f5-6618c21ed046&quot;)</value>
      <webElementGuid>64a09782-d073-4d59-92a0-cb8c61538501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      <webElementGuid>b6a2e374-862f-43ae-91fd-6daabbe2e695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/label[2]/div/div/div/input</value>
      <webElementGuid>868ea155-aedb-4948-a9aa-3e1e65cb3b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div/div/input</value>
      <webElementGuid>e57e6d8b-8380-4952-b75a-1004116b9898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_757dd486-5af3-4359-85f5-6618c21ed046' and @type = 'password']</value>
      <webElementGuid>c6c3cd20-51a3-4f21-aa8c-57d70ec3b14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
