<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StaffPINStaff</name>
   <tag></tag>
   <elementGuidId>31e72303-f919-434d-8485-54c116f2729a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Staff PIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c24f057-1027-4898-84a8-a167e6a6bafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>396bfa4b-07f7-423e-b3e1-b33d16a3537b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d3186aa7-6dce-4d3d-b471-62bd38e8c065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Staff PIN</value>
      <webElementGuid>0813698f-c361-4c56-b7bd-791dee749e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      <webElementGuid>5872fb58-7274-4368-8b05-2186b3391668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>158f3a7e-d29d-4d8f-8a36-9b051ea50248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_757dd486-5af3-4359-85f5-6618c21ed046&quot;)</value>
      <webElementGuid>6796279c-5ae0-4e76-9be2-02a9b0588bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      <webElementGuid>42444af4-0952-4614-87c5-f173b1b6c7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/label[2]/div/div/div/input</value>
      <webElementGuid>330a7540-0830-45ba-b063-7ccaee261558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div/div/input</value>
      <webElementGuid>1a6a79c0-ffbb-47c9-8dd3-4a4b0963fa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_757dd486-5af3-4359-85f5-6618c21ed046' and @type = 'password']</value>
      <webElementGuid>32d8da97-b739-46f8-9aac-c71229a79f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
