<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HourlyRateStaff</name>
   <tag></tag>
   <elementGuidId>9c7f1415-5919-43e9-9305-983a008e0dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Hourly Rate ()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2613a4f0-3754-4bec-8693-061fe3c4f795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>d4912649-7753-4c4f-8831-f0be042ffc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e0a0e06-7ed4-4d09-a0a8-9ef52fabe27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hourly Rate ()</value>
      <webElementGuid>6d6beebb-60ce-469f-a4df-103cc265398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_757dd486-5af3-4359-85f5-6618c21ed046</value>
      <webElementGuid>fd1d3699-6144-4383-af54-4c961c960ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>634f9fbc-26b0-479b-af60-f3e3f4e4d61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_757dd486-5af3-4359-85f5-6618c21ed046&quot;)</value>
      <webElementGuid>abb01995-580e-4504-95ac-9b0896e3c58d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_757dd486-5af3-4359-85f5-6618c21ed046']</value>
      <webElementGuid>c32a0a93-3e81-4dee-9e7b-2b04804cb845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/label[2]/div/div/div/input</value>
      <webElementGuid>123bb6b9-87ec-4ea6-8e26-c6123e21c3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div/div/input</value>
      <webElementGuid>14daaa9e-1864-4c0e-be7c-9c54648739f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_757dd486-5af3-4359-85f5-6618c21ed046' and @type = 'password']</value>
      <webElementGuid>4c59343e-9433-4a4a-ab04-2dc8dec81271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
