<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>51ce1b25-db24-40f0-85e5-51aacfa98b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Username' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21cdb7c3-00bf-49a2-94d8-3a6e174f63b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>ca179c15-4b11-438f-9801-5a6004271f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b536d7a7-500e-4af3-8e38-ce09eedc17fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>bec7f40c-ec24-4057-8b98-5f61a720122d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e</value>
      <webElementGuid>a421989e-a5ec-4580-8c57-e3cd0b41f35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3d9f876-33c9-4d3b-b714-3e782f5a06b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e&quot;)</value>
      <webElementGuid>493e9a78-90d0-42bd-999d-03bccc064963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e']</value>
      <webElementGuid>d90ea3aa-86fb-4524-85bc-ba6df7d99785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/label/div/div/div/input</value>
      <webElementGuid>c59672ef-ee50-4c56-aa0b-23ce1afb933e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d33a358a-7e85-4ed0-b317-38dd568416f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_3f7ac95f-11a7-4b36-816e-8ce7ae77825e' and @type = 'text']</value>
      <webElementGuid>995dc526-58eb-4b2b-8c52-cfb81c5f7472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
