<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1234</name>
   <tag></tag>
   <elementGuidId>90357a9a-aa45-40bd-a638-46083d75ea65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Awi' or . = 'Awi')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='q-app']/div/div/div[3]/div/main/div[4]/div[2]/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>96962c7e-a6a2-4ef1-a50f-fefa50b37e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-td text-left</value>
      <webElementGuid>c7ab5295-c5dd-4f51-9993-8a09f3a758a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awi</value>
      <webElementGuid>19b7d198-528a-4514-b1c7-cf39b9e41432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop no-touch body--light&quot;]/div[@id=&quot;q-app&quot;]/div[@id=&quot;q-app&quot;]/div[1]/div[@class=&quot;q-layout q-layout--standard&quot;]/div[@class=&quot;q-page-container&quot;]/div[@class=&quot;q-layout q-layout--standard&quot;]/main[@class=&quot;q-page q-layout-padding&quot;]/div[@class=&quot;q-table__container q-table--horizontal-separator column no-wrap q-table__card q-table--flat q-table--bordered q-table--no-wrap bg-grey-1 q-mt-sm&quot;]/div[@class=&quot;q-table__middle scroll&quot;]/table[@class=&quot;q-table&quot;]/tbody[1]/tr[@class=&quot;q-tr cursor-pointer&quot;]/td[@class=&quot;q-td text-left&quot;]</value>
      <webElementGuid>ebc4acd1-6017-4005-993d-5f19cded32a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div[3]/div/main/div[4]/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>9bccadeb-f517-4a61-b29a-15d5f44994f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awi'])[1]/following::td[2]</value>
      <webElementGuid>da502db9-240b-4349-858b-1fe654bfdbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records per page:'])[1]/preceding::td[1]</value>
      <webElementGuid>3e097767-a4a2-4c06-9bc9-771b8320ae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1234']/parent::*</value>
      <webElementGuid>2448646b-3ed9-48e5-bfda-af00f7643faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>8358eb7d-57fd-47b5-878d-697e57129a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1234' or . = '1234')]</value>
      <webElementGuid>2e633f93-ce87-4fc8-9f66-dfaea4803465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
